spring:
  kafka:
    producer:
      bootstrapServers: "[::1]:9092"
      topic: topic.raw
      topicOutput: topic.events
    consumer:
      bootstrapServers: "[::1]:9092"
      topic: topic.raw
      groupid: spring-kafka-consumer
  data:
    cassandra:
        keyspace-name: enrichbase
        local-datacenter: datacenter1
    port: 9042
